export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const REQUEST_FAIL = "REQUEST_FAIL";

export const GETPRODUCT_SUCCESS = "GETPRODUCT_SUCCESS";

export const POSTPRODUCT_SUCCESS = "POSTPRODUCT_SUCCESS";

export const UPDATEPRODUCT_SUCCESS = "UPDATEPRODUCT_SUCCESS";

export const DELETEPRODUCT_SUCCESS = "DELETEPRODUCT_SUCCESS";